language: node_js
node_js:
  - 10.15.2
cache: npm install
jobs:
  include:
    - stage: test
      script: 
        - npm run lint
        - npm run test
    - stage: publish
      script:
        - ./scripts/publish.sh
stages:
  - test
  - name: publish
    if: branch = master AND type != pull_request AND commit_message !~ /(Publish)/